#!/usr/bin/env bash
# Generate an RSA key pair
# Specify key parameters
private_key_name="school"
passphrase="betty"
key_bits=4096
# Generate the key pair using ssh-keygen
ssh-keygen -t rsa -b $key_bits -f $private_key_name -N $passphrase
